### ISSUE TITLE
Wrong Sprite Found

### ISSUE THREAD

**Issue by CptnBrittish** [phalt/pykemon#4]
When using the national_id to find the sprite of a pokemon (also encountered when using the resource uri with only the numbers used) the correct sprite for a pokemon is not always presented.

How to replicate:
- Search for spearow (national_id 21)
- Use national_id as resource for sprite
- Sprite presented is a Raticate

This happens for various pokemon not just spearow

**Comment by phalt** [comment]
You don't use the national ID to identify a sprite. The sprite resource are
auto-generated, they might not match up and they're not intended to either.

The best way to get the correct sprite, is to search for a Pokemon and then
get the sprite resource links from that resource. Check the docs for more
details.

**Comment by CptnBrittish** [comment]
Ahh I see now. I am sorry I normally check how to link stuff up by checking the pokeapi docs which seem more complete and that does not have a sprite resource and googling found that to be the way todo it. 
Thank you for your quick responce
